"""BibTeX 引用库读写：轻量扫描条目（查找/去重）与 append-only 追加。

references.bib 是引用库的真相源——用户手工维护的分节注释（`% ---- 主题 ----`）
须原样保留，故只追加、绝不重写。条目扫描用正则提取 key 与字段，不做完整
语法解析（够查找/去重用）。写操作持进程内锁串行：子 agent 同进程 asyncio
并发，进程内锁足够；多进程写属罕见场景，不为它上文件锁。
"""
from __future__ import annotations

import re
import threading
from dataclasses import dataclass, field
from pathlib import Path

_write_lock = threading.RLock()

_HEADER = ("% ===================================================================\n"
           "% REFERENCES - generated by paperFlow\n"
           "% 只含语料库内真实文献；库外真实文献标 EXTERNAL\n"
           "% ===================================================================\n")


@dataclass
class BibEntry:
    """一条 BibTeX 条目的最小视图（查找/去重/渲染用）。"""

    key: str
    entry_type: str = "article"
    title: str = ""
    authors: str = ""
    year: str = ""
    fields: dict = field(default_factory=dict)
    raw: str = ""          # 完整条目原文（含 @type{...}），bibtex 渲染用


def _normalize(text: str) -> str:
    """标题归一化：小写 + 去标点 + 折叠空白（全标题精确匹配的基础）。"""
    return re.sub(r"[\s\W_]+", "", text.lower())


def ensure_file(path: str | Path) -> None:
    """bib 文件不存在时创建（带头部注释）；父目录自动建。"""
    p = Path(path)
    if not p.exists():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(_HEADER, encoding="utf-8")


def _entry_body(text: str, start: int) -> str:
    """从条目体起点（条目 '{' 之后）括号配对截取到外层右括号。"""
    i, depth = start, 1
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return text[start:i]


def _fields_of(body: str) -> dict[str, str]:
    """提取条目体内的 name = {value} 字段（值内嵌套花括号按深度配对）。"""
    fields = {}
    for m in re.finditer(r"(\w+)\s*=\s*\{", body):
        name = m.group(1)
        j, d = m.end(), 1
        while j < len(body):
            if body[j] == "{":
                d += 1
            elif body[j] == "}":
                d -= 1
                if d == 0:
                    break
            j += 1
        fields[name] = body[m.end():j].strip()
    return fields


def parse_entries(path: str | Path) -> list[BibEntry]:
    """扫描 bib 文件返回条目列表；文件不存在/空 → 空列表。

    条目起始 ``@type{key,``，字段按括号配对提取（不解析嵌套语法）。
    raw 保留条目原文（含 @type{...} 到配对右括号），供 bibtex 渲染。
    """
    p = Path(path)
    if not p.exists():
        return []
    text = p.read_text(encoding="utf-8")
    entries = []
    for m in re.finditer(r"@(\w+)\s*\{([^,{]+)\s*,", text):
        entry_type, key = m.group(1), m.group(2).strip()
        body = _entry_body(text, m.end())
        fields = _fields_of(body)
        entries.append(BibEntry(
            key=key, entry_type=entry_type,
            title=fields.get("title", ""),
            authors=fields.get("author", ""),
            year=fields.get("year", ""),
            fields=fields,
            raw=f"@{entry_type}{{{key},{body}}}",
        ))
    return entries


def find_by_title(path: str | Path, title: str) -> BibEntry | None:
    """按标题找条目（归一化比较）；用于去重。无命中返回 None。"""
    norm = _normalize(title)
    for e in parse_entries(path):
        if e.title and _normalize(e.title) == norm:
            return e
    return None


def append_entry(path: str | Path, entry_text: str) -> None:
    """追加一条已格式化的 bib 条目（append-only，保留原内容与注释）。"""
    p = Path(path)
    ensure_file(p)
    text = entry_text if entry_text.endswith("\n") else entry_text + "\n"
    with _write_lock:
        with open(p, "a", encoding="utf-8") as f:
            f.write("\n" + text)
