"""BibTeX 引用库读写：轻量扫描条目（查找/去重）与 append-only 追加。

references.bib 是引用库的真相源——用户手工维护的分节注释（`% ---- 主题 ----`）
须原样保留。写入只有两种原语：append-only 追加（append_entry，只在文件末尾
添加）与按 key 的整块删除（remove_entries，只移除命中条目的原文块）；两者都
不重新序列化其余内容，注释与未触碰条目的原文逐字节保留。条目扫描用正则提取
key 与字段，不做完整语法解析（够查找/去重用）。写操作持进程内锁串行：子
agent 同进程 asyncio 并发，进程内锁足够；多进程写属罕见场景，不为它上文件锁。

--------------------------------------------------------------------
BibTeX 格式速览（本模块注释术语对照）

references.bib 由一摞「条目」（entry，一张图书卡片）组成，一条条目长这样：

    @article{vaswani2017attention,          <- 条目头：类型 + key
      author  = {Vaswani, Ashish},          +\
      title   = {Attention Is All You Need, | 条目体（body）：
      journal = {NeurIPS},                  | 一摞字段（field）
      year    = {2017},                     +/
    }                                       <- 配对右括号

- 条目类型（entry_type）：@article 期刊论文 / @inproceedings 会议论文 / @book 书……@ 是 BibTeX 的条目起始标记。
- key（引用键）：卡片的唯一编号（如 "vaswani2017attention" =
  一作姓氏 + 年份 + 短标题，见 manager.gen_key）。LaTeX 的 cite 命令、
  笔记的 [来源:key§节] 标注都用它指名道姓。
- 条目体（body）：除去 `@type{key,` 头之后、直到配对右括号之间的全部内容。
- 字段（field）：一行属性 `name = {value}`（author/title/year/journal…）。
- raw（条目原文）：从 @ 到配对 } 的完整原文，一个字符不加工；bibtex 渲染样式时原样吐回。

花括号配对（_entry_body / _fields_of 的深度计数）：BibTeX 的值内可嵌套花括号（如 {Attention Is {All} You Need}，内层 {} 保护大写），
不能"见 } 就停"——从 { 出发，遇 { depth+1、遇 } depth-1，depth 回到 0 才是真结束。
两个函数是同一算法的两个层级：_entry_body 对整张卡片截体，_fields_of 对卡片里每行属性抠值。

函数地图：
    ensure_file     文件不存在则建空文件（写入头部注释）
    parse_entries   全文件扫描：正则找条目头 -> _entry_body 截体 ->
                    _fields_of 抠字段 -> 组装 BibEntry 列表
    find_by_title   按标题查找/去重；先 _normalize（小写+去标点+折叠空白），
                    大小写与标点差异不影响"同标题"判定
    append_entry    锁内往文件末尾追加一条条目（append-only，不重写）
    remove_entries  按 key 集合整块删除条目原文（其余内容逐字节保留），
                    返回实际删除的 key 列表
    find_all_by_title
                    按标题查找全部命中（归一化比较）；删除前多条命中检测用

边界：条目头必须严格是 `@type{key,`（key 后紧跟逗号）才能被识别；不解析 @string 宏等完整语法——对查找/去重/原文渲染三个用途足够。
--------------------------------------------------------------------
"""
from __future__ import annotations

import re
import threading
from dataclasses import dataclass, field
from pathlib import Path

_write_lock = threading.RLock()

_HEADER = ("% ===================================================================\n"
           "% REFERENCES - generated by paperFlow\n"
           "% 只含语料库内真实文献；库外真实文献标 EXTERNAL\n"
           "% ===================================================================\n")


@dataclass
class BibEntry:
    """一条 BibTeX 条目的最小视图（查找/去重/渲染用）。

    Attributes:
        key: str，引用键（条目唯一编号）
        entry_type: str，条目类型（article/inproceedings/book…）
        title: str，标题字段
        authors: str，author 字段原文
        year: str，year 字段
        fields: dict，全部字段名 → 值
        raw: str，条目原文（@type{...} 到配对右括号，bibtex 渲染用）
    """

    key: str
    entry_type: str = "article"
    title: str = ""
    authors: str = ""
    year: str = ""
    fields: dict = field(default_factory=dict)
    raw: str = ""          # 完整条目原文（含 @type{...}），bibtex 渲染用


def _normalize(text: str) -> str:
    """标题归一化：小写 + 去标点 + 折叠空白（全标题精确匹配的基础）。

    Args:
        text: str，待归一化文本（通常为标题）

    Returns:
        小写、去标点、折叠空白后的字符串（全标题精确匹配的基础）。
    """
    return re.sub(r"[\s\W_]+", "", text.lower())


def ensure_file(path: str | Path) -> None:
    """bib 文件不存在时创建（带头部注释）；父目录自动建。

    Args:
        path: bib 文件的路径（字符串或 Path 对象）。
    """
    p = Path(path)
    with _write_lock:
        if not p.exists():
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(_HEADER, encoding="utf-8")


def _entry_body(text: str, start: int) -> str:
    """从条目体起点（条目 '{' 之后）括号配对截取到外层右括号。

    Args:
        text: 完整的 bib 文件内容。
        start: 条目 `{` 之后的下标（即 `m.end()`，指向体开始）。

    Returns:
        括号配对截取到的字符串（不含最外层右括号，即从 `start` 到配对 `}` 之前的内容）。
    """
    i, depth = start, 1
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return text[start:i]


def _fields_of(body: str) -> dict[str, str]:
    """提取条目体内的 name = {value} 字段（值内嵌套花括号按深度配对）。

    Args:
        body: 条目的体内容（不含 `@type{key,` 前缀，也不含最外层右括号）。

    Returns:
        字段名到字段值的字典。字段值去掉了外层花括号。
    """
    fields = {}
    for m in re.finditer(r"(\w+)\s*=\s*\{", body):
        name = m.group(1)
        j, d = m.end(), 1
        # 括号深度计数，找到配对关闭的花括号
        while j < len(body):
            if body[j] == "{":
                d += 1
            elif body[j] == "}":
                d -= 1
                if d == 0:
                    break
            j += 1
        fields[name] = body[m.end():j].strip()
    return fields


def parse_entries(path: str | Path) -> list[BibEntry]:
    """扫描 bib 文件返回条目列表；文件不存在/空 → 空列表。

    条目起始 ``@type{key,``，字段按括号配对提取（不解析嵌套语法）。
    raw 保留条目原文（含 @type{...} 到配对右括号），供 bibtex 渲染。

    Args:
        path: bib 文件路径。

    Returns:
        解析出的 `BibEntry` 列表。若文件不存在或为空，返回空列表。

    边界：
        - 条目必须严格遵循 `@type{key,` 格式，key 后紧跟逗号，否则无法识别。
        - 若条目体内有非字段的花括号，不影响字段提取（按深度配对）。
        - 读时持模块级 `_write_lock`：与写入互斥，不会读到写了一半的文件。
    """
    p = Path(path)
    # 读方与写方共用这把锁：写（append / remove）在锁内落盘，读者等它写完再取内容，
    # 因此不会读到写了一半的 bib。只把「取到完整文本」放进临界区，解析在锁外做。
    with _write_lock:
        if not p.exists():
            return []
        text = p.read_text(encoding="utf-8")
    entries = []
    # 匹配 `@类型{键,` 注意 key 不能包含逗号和花括号
    for m in re.finditer(r"@(\w+)\s*\{([^,{]+)\s*,", text):
        entry_type, key = m.group(1), m.group(2).strip()
        body = _entry_body(text, m.end())
        fields = _fields_of(body)
        entries.append(BibEntry(
            key=key, entry_type=entry_type,
            title=fields.get("title", ""),
            authors=fields.get("author", ""),
            year=fields.get("year", ""),
            fields=fields,
            raw=f"@{entry_type}{{{key},{body}}}",
        ))
    return entries


def find_by_title(path: str | Path, title: str) -> BibEntry | None:
    """按标题找条目（归一化比较）；用于去重。无命中返回 None。

    Args:
        path: bib 文件路径。
        title: 待匹配的标题（原始字符串，函数内部归一化）。

    Returns:
        匹配的 `BibEntry` 对象，若未命中返回 `None`。
    """
    norm = _normalize(title)
    for e in parse_entries(path):
        if e.title and _normalize(e.title) == norm:
            return e
    return None


def append_entry(path: str | Path, entry_text: str) -> None:
    """追加一条已格式化的 bib 条目（append-only，保留原内容与注释）。

    不会重写现有内容，保留用户手工添加的分节注释。若文件不存在则先创建。
    追加前确保条目以换行结尾，避免与后续内容粘连。
    写操作持进程内可重入锁，防止同一进程内并发写冲突。

    Args:
        path: bib 文件路径。
        entry_text: 完整的 BibTeX 条目文本（可含前导注释，但建议不含尾部多余换行）。
                    函数会自动补一个换行符，并前导一个空行以分隔条目。

    线程安全：使用 `_write_lock` (RLock) 保护写入操作，同一进程内任意线程串行。
              多进程同时写入不会阻塞，但在正常使用中极少发生，故未加文件锁。
    """
    p = Path(path)
    ensure_file(p)
    text = entry_text if entry_text.endswith("\n") else entry_text + "\n"
    with _write_lock:
        with open(p, "a", encoding="utf-8") as f:
            f.write("\n" + text)


def _collapse_seam(left: str, right: str) -> str:
    """把删除接缝两侧的连续空行压到至多一个；不扩张原本的空行。

    接缝 = 被删条目原本占据的拼接点：left 是其前一段原文，right 是其后一段。
    只处理两侧首尾的换行，left/right 的内部内容原样保留——这样删除目标之外的
    区域（含用户手工分节注释、无关注释区的连续空行）逐字节不动。原本不足两个
    换行的接缝不做扩张，避免制造出原文没有的空行。

    Args:
        left: str，删除接缝左侧原文
        right: str，删除接缝右侧原文

    Returns:
        接缝两侧连续空行压到至多一个后的拼接文本（内部内容逐字节保留）。
    """
    left_body = left.rstrip("\n")
    right_body = right.lstrip("\n")
    newlines = (len(left) - len(left_body)) + (len(right) - len(right_body))
    return left_body + "\n" * min(newlines, 2) + right_body


def remove_entries(path: str | Path, keys: set[str]) -> list[str]:
    """按 key 删除条目：逐条定位原文块整段删除，其余内容逐字节保留。

    与 append-only 追加互补的删除原语。删除粒度是「条目原文块」——从
    `@type{key,` 头到配对右括号整段移除，条目之间的分节注释、其余条目的
    原文（含字段排布与花括号嵌套）一律不动，避免重新序列化造成格式损失。
    删除接缝处被删条目两侧多余的连续空行会收敛为一个空行（不留过大空隙），
    收敛只作用于接缝，文件其余区域逐字节不变。

    Args:
        path: bib 文件路径。
        keys: 待删除的条目 key 集合。

    Returns:
        实际删除的 key 列表（文件中未命中的 key 不在其中）。
    """
    p = Path(path)
    if not p.exists() or not keys:
        return []
    text = p.read_text(encoding="utf-8")
    spans, removed = [], []
    for m in re.finditer(r"@(\w+)\s*\{([^,{]+)\s*,", text):
        key = m.group(2).strip()
        if key not in keys:
            continue
        body = _entry_body(text, m.end())
        spans.append((m.start(), m.end() + len(body) + 1))   # +1 吃掉配对右括号
        removed.append(key)
    if not removed:
        return []
    out, prev = [], 0
    for start, end in spans:
        out.append(text[prev:start])
        prev = end
    out.append(text[prev:])
    # 逐接缝拼接：空行收敛只发生在删除点，不全局 re.sub（否则会压缩与删除
    # 无关区域的连续空行，破坏「其余内容逐字节保留」契约）
    new_text = out[0]
    for segment in out[1:]:
        new_text = _collapse_seam(new_text, segment)
    with _write_lock:
        p.write_text(new_text, encoding="utf-8")
    return removed


def find_all_by_title(path: str | Path, title: str) -> list[BibEntry]:
    """按标题找全部命中条目（归一化比较），用于删除前的多条命中检测。

    与 find_by_title 的区别：find_by_title 取首个命中（去重场景够用），
    本函数返回全量命中——删除操作面对多条命中必须交给上层澄清，不能猜。

    Args:
        path: bib 文件路径。
        title: 待匹配标题（内部归一化）。

    Returns:
        归一化标题相等（可能为空）的 `BibEntry` 列表。
    """
    norm = _normalize(title)
    return [e for e in parse_entries(path) if e.title and _normalize(e.title) == norm]
